[book]
authors = ["wbigger"]
language = "it"
multilingual = false
src = "src"
title = "TPSI - Quinto anno"

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/wbigger/book-tpsi-5y/"
